### ISSUE TITLE
在使用过程中报这个错误，应该是commit导致的

### ISSUE THREAD

**Issue by LiLinXiang** [SupLuo/HaloPermission#1]
java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:, request=4369, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.***.ms.***/halo.android.permission.caller.PermissionRequestActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

**Comment by uni-cstar** [comment]
麻烦贴一下你的调用代码，谢谢

**Comment by uni-cstar** [comment]
不能在回调中添加Fragment，比如显示DialogFragment。
