### ISSUE TITLE
编译错误 !zip.isFile()

### ISSUE THREAD

**Issue by ggggxiaolong** [SupLuo/HaloPermission#2]
Caused by: java.lang.IllegalArgumentException: !zip.isFile()
gradle 4.8
AGP：3.2.0-beta01
build_versions.min_sdk = 21
build_versions.target_sdk = 28
build_versions.compile_sdk = 28
build_versions.build_tools = "28.0.0"

**Comment by uni-cstar** [comment]
这是因为AGP版本引起的，在禁用Instant Run之后，这个错误就会消失（操作步骤Android Studio -> Preferences -> Instant Run）。
谷歌表示会在Beta-02版本中修复此问题，或者你可以暂时先使用其他版本进行编译。
>The error vanished, after disabling Instant Run.
`Android Studio -> Preferences -> Instant Run`
Google has indicated that they are going to fix it in Beta-02
https://issuetracker.google.com/issues/110564390

具体可见：https://stackoverflow.com/questions/51090828/android-studio-3-2-beta-1-zip-isfile-error
